CREATE TABLE IF NOT EXISTS CUSTOMER (ID INT, NAME VARCHAR(25), REFEREE_ID INT)
TRUNCATE TABLE CUSTOMER
INSERT INTO CUSTOMER (ID, NAME, REFEREE_ID) VALUES ('1', 'WILL', 'NONE')
INSERT INTO CUSTOMER (ID, NAME, REFEREE_ID) VALUES ('2', 'JANE', 'NONE')
INSERT INTO CUSTOMER (ID, NAME, REFEREE_ID) VALUES ('3', 'ALEX', '2')
INSERT INTO CUSTOMER (ID, NAME, REFEREE_ID) VALUES ('4', 'BILL', 'NONE')
INSERT INTO CUSTOMER (ID, NAME, REFEREE_ID) VALUES ('5', 'ZACK', '1')
INSERT INTO CUSTOMER (ID, NAME, REFEREE_ID) VALUES ('6', 'MARK', '2')

SELECT NAME
    FROM CUSTOMER 
    WHERE REFEREE_ID IS NULL OR REFEREE_ID != 2