CREATE TABLE IF NOT EXISTS PRODUCTS (PRODUCT_ID INT, LOW_FATS ENUM('Y', 'N'), RECYCLABLE ENUM('Y','N'))
TRUNCATE TABLE PRODUCTS
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE) VALUES ('0', 'Y', 'N')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE) VALUES ('1', 'Y', 'Y')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE) VALUES ('2', 'N', 'Y')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE) VALUES ('3', 'Y', 'Y')
INSERT INTO PRODUCTS (PRODUCT_ID, LOW_FATS, RECYCLABLE) VALUES ('4', 'N', 'N')

SELECT PRODUCT_ID FROM PRODUCTS WHERE LOW_FATS = 'Y' AND RECYCLABLE = 'Y'