CREATE TABLE IF NOT EXISTS PERSON (ID INT, EMAIL VARCHAR(255))
TRUNCATE TABLE PERSON
INSERT INTO PERSON (ID, EMAIL) VALUES ('1', 'JOHN@EXAMPLE.COM')
INSERT INTO PERSON (ID, EMAIL) VALUES ('2', 'BOB@EXAMPLE.COM')
INSERT INTO PERSON (ID, EMAIL) VALUES ('3', 'JOHN@EXAMPLE.COM')

WITH 
CTE AS (
    SELECT * ,
        ROW_NUMBER() OVER (PARTITION BY EMAIL ORDER BY ID) RN
        FROM PERSON
) 

DELETE P FROM PERSON P, CTE C WHERE C.RN > 1 AND P.ID = C.ID