CREATE TABLE IF NOT EXISTS SALARY (ID INT, NAME VARCHAR(100), SEX CHAR(1), SALARY INT)
TRUNCATE TABLE SALARY
INSERT INTO SALARY (ID, NAME, SEX, SALARY) VALUES ('1', 'A', 'M', '2500')
INSERT INTO SALARY (ID, NAME, SEX, SALARY) VALUES ('2', 'B', 'F', '1500')
INSERT INTO SALARY (ID, NAME, SEX, SALARY) VALUES ('3', 'C', 'M', '5500')
INSERT INTO SALARY (ID, NAME, SEX, SALARY) VALUES ('4', 'D', 'F', '500')

UPDATE SALARY
SET SEX = (CASE WHEN SEX = 'm' THEN 'f' ELSE 'm' END)