CREATE TABLE IF NOT EXISTS CUSTOMERS (ID INT, NAME VARCHAR(255))
CREATE TABLE IF NOT EXISTS ORDERS (ID INT, CUSTOMERID INT)
TRUNCATE TABLE CUSTOMERS
INSERT INTO CUSTOMERS (ID, NAME) VALUES ('1', 'JOE')
INSERT INTO CUSTOMERS (ID, NAME) VALUES ('2', 'HENRY')
INSERT INTO CUSTOMERS (ID, NAME) VALUES ('3', 'SAM')
INSERT INTO CUSTOMERS (ID, NAME) VALUES ('4', 'MAX')
TRUNCATE TABLE ORDERS
INSERT INTO ORDERS (ID, CUSTOMERID) VALUES ('1', '3')
INSERT INTO ORDERS (ID, CUSTOMERID) VALUES ('2', '1')

SELECT NAME AS CUSTOMERS 
    FROM CUSTOMERS 
    WHERE 
        ID NOT IN (
            SELECT CUSTOMERID 
                FROM ORDERS 
                GROUP BY CUSTOMERID
            )